### ISSUE TITLE
Work Elections Survey Emails to Local Jurisdictions - New HTML update

### ISSUE THREAD

**Issue by nayelipelayo** [developmentseed/work.vote#107]
1. Is it possible to add a BCC function so that recipients don't see all the emails included in the email 

2. Is it possible to include a plain text editor so that we can see what the plain text message will look like and be able to clean up formatting issues before sending off. 

3. The HTML has buttons for jurisdictions, can we have buttons appear instead of links?

[beefree-lhcyk7pkpa (3).zip](https://github.com/developmentseed/work.vote/files/2461802/beefree-lhcyk7pkpa.3.zip)

**Comment by alyssadelaine** [comment]
Hi @nayelipelayo, this is an issue on the backend, so I'm going to move it there and tag you in the new issue
