### ISSUE TITLE
Commit history

### ISSUE THREAD

**Issue by scisco** [developmentseed/work.vote#3]
@laurencjay @DylanMoriarty It seems that the git history of my master differed from the git history of the code based that was later merged by Lauren which overrode a few of the files and also added the project seed history to the git history tree again.

I'm going to fix this but in order for this to work, please make sure to `git clone` from master again before committing to the project.

**Comment by laurencjay** [comment]
Thanks @scisco for fixing this!

**Comment by scisco** [comment]
ok, commit history is fixed. @laurencjay please do not merge the `lauren-master` to develop or master as it includes a git history that we don't want to add to our git tree.

Also, let's use develop as the main branch. The workflow is to PR to develop and then from develop to master for production release.
