### ISSUE TITLE
Edits to the jurisdiction finder info

### ISSUE THREAD

**Issue by laurencjay** [developmentseed/work.vote#34]
Edits to make to the jurisdiction finder per our conversation with FELN: 

**In General:**

From what we talked about at the end of the meeting, we need to think about the best way to present this information in a synthesized manner whether that's bullets or what have you. Additionally, this may be a place where we want to include some small graphics @DylanMoriarty.

Fixes FELN mentioned:
    - Nix high school students
    - Nix Age Restrictions
    - Start Time: End Time: separated
    - Registration: Have it pull city or county (or shorten the sentence) based on the jurisdiction type
    - If blank, nothing show up, if Y-you must be preregistered to vote 
    - More bulleted under requirements 
    - Email being dropped, we need to include it
    - Have the link to return say "Return to homepage" instead of "Return to jurisdiction finder"
    
Other Additions: 
    - Export to PDF version
    - Print version

**Comment by scisco** [comment]
All in the list implemented.

What's left:

- Export to PDF version
- Print version

**Comment by scisco** [comment]
We decided against having pdf version at this point
