### ISSUE TITLE
Font snapshot with garamond 

### ISSUE THREAD

**Issue by laurencjay** [developmentseed/work.vote#36]
To send over to FELN to compare with Monserrat @DylanMoriarty

**Comment by DylanMoriarty** [comment]
<img width="432" alt="screenshot 2016-01-04 10 33 19" src="https://cloud.githubusercontent.com/assets/9341928/12149193/580a035c-b470-11e5-99d6-1968f1071ef3.png">
Garamond!

Ultimately, if it there was a Google Font bolder version of this, I'd like it more. As it is, it's on the thin side and while it's more friendly & personable, it doesn't really jive with the rest of the header.

<img width="1234" alt="screenshot 2016-01-06 12 29 28" src="https://cloud.githubusercontent.com/assets/9341928/12149265/d4ae93d2-b470-11e5-8958-e5a585b086b8.png">

**Comment by scisco** [comment]
sent
