### ISSUE TITLE
Update email on contact form

### ISSUE THREAD

**Issue by nayelipelayo** [developmentseed/work.vote#83]
https://www.workelections.com/contact

Please change the email from info@fairelectionsnetwork.com to info@fairelectionscenter.org

**Comment by alyssadelaine** [comment]
@nayelipelayo I just fixed this; could you check to make sure it's right?

**Comment by nayelipelayo** [comment]
Hi @alyssadelaine , it's still isted as info@fairelectionsnetwork.com

**Comment by alyssadelaine** [comment]
Thanks @nayelipelayo, I'll take another look
