### ISSUE TITLE
Google Analytics - self-referral traffic

### ISSUE THREAD

**Issue by nayelipelayo** [developmentseed/work.vote#88]
The acquisition part of our website is incorrect. Most of the direct traffic GA is showing is self-referral traffic that originates from pages within our own domain. 

Note from Google: In general, self-referrals indicate that there are Analytics implementation problems on your site.

If you're receiving self-referrals, that may mean that traffic to your site is being attributed incorrectly, or that your session count is inaccurate. There are a few different implementation problems that can cause self-referrals.

**Comment by scisco** [comment]
Thanks for catching this. I'll do some exploration. I did look at the google analytics and I didn't find anything suspicious though.

**Comment by nayelipelayo** [comment]
Okay, I'm going to close this then. Thank you.
