### ISSUE TITLE
Jurisdiction pages need name in link

### ISSUE THREAD

**Issue by nayelipelayo** [developmentseed/work.vote#99]
Currently jurisdictions are name using this convention: https://www.workelections.com/j/77

This doesn't indicate a specific jurisdiction, such as Los Angeles County. It make it difficult to analyze data in Google Analytics and doesn't help SEO ranking.

Can we redo naming convention to be: https://www.workelections.com/j/los-angeles-county, or something like that?

**Comment by anniesullie** [comment]
This is now **Fixed**
